### ISSUE TITLE
TypeScript的tsx文件好像不起作用

### ISSUE THREAD

**Issue by Skycweb** [mr18/react-i18n-auto#10]
TypeScript的tsx文件好像不起作用

**Comment by mr18** [comment]
升级到最新版本（v1.3.1），已添加对ts的支持

**Comment by Skycweb** [comment]
兄弟,默认的解析器,解析不了ts语法,文件带有private关键字解析不出来,我改了下代码,你看下有空再兼容进去.
文件:src/generator/tabelrc.js
`/**
 *
 * @type {{plugins: [string,null,string,string,string,string,string,string,string,string,string]}}
 */
module.exports = {
  plugins: [
    '@babel/plugin-syntax-jsx',
    ['@babel/plugin-proposal-decorators', { 'legacy': true }],
    '@babel/plugin-syntax-class-properties',
    '@babel/plugin-syntax-object-rest-spread',
    '@babel/plugin-syntax-async-generators',
    '@babel/plugin-syntax-do-expressions',
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-syntax-export-extensions',
    '@babel/plugin-syntax-flow',
    '@babel/plugin-syntax-function-bind',
    '@babel/plugin-syntax-function-sent'
  ]
  ,
  presets: ["@babel/preset-typescript","@babel/preset-react"]
}`

文件:src/generator/index.js
`/**
 *
 * @param options
 */
const transformCode = function (options) {
  let srcDir = options.src;
  if (typeof srcDir === "string") {
    srcDir = [srcDir];
  }
  srcDir.forEach((src) => {
    let fileList = fileUtils.getFileList(src || "");
    fileList.forEach((filePath) => {
      let isInclude = true,
        isExcluded = false;
      if (options.include) {
        isInclude = options.include.test(filePath);
      }
      if (options.excluded) {
        isExcluded = options.excluded.test(filePath);
      }

      if (isInclude && !isExcluded) {
        let babelConfig = options.babelrc
          ? options.babelrc === true
            ? { babelrc: true }
            : Object.assign(options.babelrc, { babelrc: false })
          : {
              babelrc: false,
              plugins: [].concat(babelrc.plugins, [[plugin, options.pluginOptions || {}]]),
              presets:options.presets
            };
        let babelObj = babel.transformFileSync(filePath, babelConfig);
        if (options._test) {
          let newFilePath = filePath.replace(src, "");
          let output = path.resolve(options.outputPath, "./compile" + newFilePath);
          fileUtils.writeFile(output, babelObj.code);
        }
      }
    });
  });
};
`

**Comment by Skycweb** [comment]
兄弟,默认的解析器,解析不了ts语法,文件带有private关键字解析不出来,我改了下代码,你看下有空再兼容进去.
文件:src/generator/tabelrc.js
`/**
*

@type {{plugins: [string,null,string,string,string,string,string,string,string,string,string]}}
*/
module.exports = {
plugins: [
'@babel/plugin-syntax-jsx',
['@babel/plugin-proposal-decorators', { 'legacy': true }],
'@babel/plugin-syntax-class-properties',
'@babel/plugin-syntax-object-rest-spread',
'@babel/plugin-syntax-async-generators',
'@babel/plugin-syntax-do-expressions',
'@babel/plugin-syntax-dynamic-import',
'@babel/plugin-syntax-export-extensions',
'@babel/plugin-syntax-flow',
'@babel/plugin-syntax-function-bind',
'@babel/plugin-syntax-function-sent'
]
,
presets: ["@babel/preset-typescript","@babel/preset-react"]
}`
文件:src/generator/index.js
`/**
*

@param options
*/
const transformCode = function (options) {
let srcDir = options.src;
if (typeof srcDir === "string") {
srcDir = [srcDir];
}
srcDir.forEach((src) => {
let fileList = fileUtils.getFileList(src || "");
fileList.forEach((filePath) => {
let isInclude = true,
isExcluded = false;
if (options.include) {
isInclude = options.include.test(filePath);
}
if (options.excluded) {
isExcluded = options.excluded.test(filePath);
}

if (isInclude && !isExcluded) {
let babelConfig = options.babelrc
? options.babelrc === true
? { babelrc: true }
: Object.assign(options.babelrc, { babelrc: false })
: {
babelrc: false,
plugins: [].concat(babelrc.plugins, [[plugin, options.pluginOptions || {}]]),
presets:babelrc.presets
};
let babelObj = babel.transformFileSync(filePath, babelConfig);
if (options._test) {
let newFilePath = filePath.replace(src, "");
let output = path.resolve(options.outputPath, "./compile" + newFilePath);
fileUtils.writeFile(output, babelObj.code);
}
}
});
});
};
`

**Comment by mr18** [comment]
i18n.config.js配置babelrc: true，使用当前项目配置即可~
