### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by wx9999** [mr18/react-i18n-auto#5]
Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined

**Comment by mr18** [comment]
确少NODE_ENV变量，可以在webpack中添加配置

**Comment by mr18** [comment]
` cross-env NODE_ENV=production node ./i18n.config.js ` ，使用 `cross-env` 设置 `NODE_ENV`
