### ISSUE TITLE
Throwing an Error when execute `node i18n.config.js`

### ISSUE THREAD

**Issue by sxiong5** [mr18/react-i18n-auto#8]
After adding the babel config and executing `node i18n.config.js`, it throws an error: 

Error: [BABEL] D:\Library\Project\Desk\src\App.test.js: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined. (While processing: "D:\\Library\\Project\\Desk\\node_modules\\babel-preset-react-app\\index.js")

![image](https://user-images.githubusercontent.com/62367016/142346010-4d318d12-5f49-495f-9397-dc171921cbcc.png)

My babel config is like this:
![image](https://user-images.githubusercontent.com/62367016/142346123-8e100ccf-d2b9-41b3-bd3c-ea37570d5c92.png)

**Comment by mr18** [comment]
#5

**Comment by mr18** [comment]
new webpack.DefinePlugin({
      "process.env": {
        NODE_ENV: JSON.stringify("development"),
      },
    })

**Comment by mr18** [comment]
` cross-env NODE_ENV=production node ./i18n.config.js ` ，使用 `cross-env` 设置 `NODE_ENV`
