### ISSUE TITLE
Can not operate  node i18n.config.js 

### ISSUE THREAD

**Issue by yixiaosi1314** [mr18/react-i18n-auto#9]
![image](https://user-images.githubusercontent.com/81505326/146740308-c990a827-d728-4d21-9319-17421cb00d03.png)
demo run node i18n.config.js Keep reporting errors, no matter how you modify it, you can’t proceed to the next step

**Comment by yixiaosi1314** [comment]
![image](https://user-images.githubusercontent.com/81505326/146744696-d66f8ba1-c3d0-4152-9a0b-cf9518b4f473.png)
There is no language pack file here

**Comment by mr18** [comment]
upgrade to version 1.2.2

**Comment by yixiaosi1314** [comment]
The current version is 1.2.2. I solved the problem by manually adding the .xlsx file, but now the compilation is completed but the result I want is not achieved, and there is no change.
![image](https://user-images.githubusercontent.com/81505326/146897562-5c16ffa8-de0e-45d7-897b-b6a43c86a340.png)

**Comment by yixiaosi1314** [comment]
Is there any step I missed?

**Comment by mr18** [comment]
It's no effects on the source code, you can check the compiled code.

**Comment by yixiaosi1314** [comment]
![image](https://user-images.githubusercontent.com/81505326/147544690-c8652028-d23f-4342-b504-3ec340f50526.png)
Do you mean this is the effect after success?

**Comment by yixiaosi1314** [comment]
![image](https://user-images.githubusercontent.com/81505326/147545316-ea8a7732-9d58-4eb5-937f-72ce53e23c8f.png)
There hasn’t been any changes to this page either

**Comment by mr18** [comment]
yes,It's only effects on script files

**Comment by yixiaosi1314** [comment]
这个还是不知道运用到实际项目当中去啊，我完全按照教程来的，但是我的项目中打包还是没有实现这样的效果，是不是因为打包的配置文件的原因啊

**Comment by mr18** [comment]
> 这个还是不知道运用到实际项目当中去啊，我完全按照教程来的，但是我的项目中打包还是没有实现这样的效果，是不是因为打包的配置文件的原因啊

加上翻译文件了吗？

**Comment by mr18** [comment]
![image](https://user-images.githubusercontent.com/4214624/148200324-5fac6be6-72d9-410a-ad70-6fd5c69dcbeb.png)

**Comment by yixiaosi1314** [comment]
加了，大佬，我能加你一个联系方式吗，做了两周，也没有达到预期的效果，这个问题困扰我半个月了，等你有时间的时候想向你请教一下

**Comment by mr18** [comment]
email: zhou060860@163.com

**Comment by yixiaosi1314** [comment]
好的，感谢大佬，等有时间再向您请教

**Comment by mr18** [comment]
对照下git上的 [DEMO](./demo)
